# Generated by Django 5.0.6 on 2024-07-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bus_no', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
                ('bus_type', models.CharField(max_length=100)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
