# Generated by Django 5.0.6 on 2024-07-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
